version: '3.9'
name: production

services:
  # only for dev / testing purposes
  db_backup:
    build: .
    command: ./db_backup -b weekly
    volumes:
      - ./ztest/srv:/srv
      - /var/run/docker.sock:/var/run/docker.sock
